### ISSUE TITLE
Complete Input Fields for the FAQ Page

### ISSUE THREAD

**Issue by Niwri** [UTFO/teaparty-admin#11]
As with the Home page, complete the input fields for the FAQ Page. Ensure that GET, PUT, and POST requests work as intended.

Also ensure that the design for the input modal view in each page are similar.

![image](https://github.com/UTFO/teaparty-admin/assets/60520263/5a53ece1-1d02-4aa7-af94-3f2b1f86ae66)

**Comment by Zazzscoot** [comment]
prereqs incomplete?
